name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.7']

    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v3
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v3
      - name: Checkout xnat-docker-compose
        uses: actions/checkout@v3
        with:
          repository: NrgXnat/xnat-docker-compose
          ref: 1.8.1
          path: xnat-docker-compose
      - run: docker-compose --version
      - run: python --version
      - run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Install sphinx
        run: pip install sphinx sphinx_theme
        if: ${{ matrix.python-version == '3.7' }}
      - name: Start xnat-docker-compose
        run: docker-compose up -d
        working-directory: xnat-docker-compose
      - run: sleep 120
      - name: Check xnat-docker-compose
        run: docker-compose logs --tail=20 xnat-web
        working-directory: xnat-docker-compose
      - name: Run tests (nose)
        run: nosetests pyxnat/tests --nologcapture --with-coverage --cover-inclusive --cover-erase --cover-package .
        env:
          PYTHONPATH: $PYTHONPATH:$(pwd)
      - name: Coveralls
        #uses: coverallsapp/github-action@master
        #with:
        #  github-token: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.7']

    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v3
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v3
      - run: python --version
      - run: python -m pip install --upgrade pip
      - name: Install sphinx
        run: pip install sphinx sphinx_theme
      - name: Build docs
        run: ./build-docs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}